<?php
class PDF extends FPDF
{
	//En-tête
	function Header()
	{
		
	}
	
	//Pied de page
	function Footer()
	{
		//Positionnement à 1,5 cm du bas
		$this->SetY(-15);
		//Police Arial italique 8
		$this->SetFont('Arial','I',8);
		//Numéro de page
		$this->Cell(110,10,'Page '.$this->PageNo().'/{nb}',0,0,'R');
			//Décalage à droite
		//$this->Cell(20);
		//Titre
		$this->Cell(80,10, "Generated by Portfolio 1.0",0,0,'R');
}

	function EnteteReleveComptes($titre, $texte, $logo) {
		$this->Image($logo,10,8,33);
		$this->SetFont('Arial','B',15);
		$this->Cell(80);
		$this->Cell(30, 10, $titre, 0, 0, 'C');
		$this->Ln(18);
		$this->SetFont('Arial','',9);
                $this->Cell(180, 7, $texte, 0, 0, 'L', 0);
		$this->Ln();
	} 

	function EnteteTableau($header,$w, $couleur) {
		$this->SetFillColor($couleur[0], $couleur[1], $couleur[2]);
		$this->SetTextColor(255);
		$this->SetDrawColor($couleur[0], $couleur[1], $couleur[2]);
		$this->SetLineWidth(.3);
		$this->SetFont('','B');
		for($i=0;$i<count($header);$i++)
		$this->Cell($w[$i],7,$header[$i],1,0,'C',1);
		$this->Ln();
	} 
	
	//Tableau coloré
	function FancyCell($row, $w)
	{
		//Restauration des couleurs et de la police
		$this->SetFillColor(0);
		$this->SetTextColor(0);
		$this->SetFont('');
		$this->SetLineWidth(.3);
		$this->SetDrawColor(0,0,100);
		//Données
		$this->Cell($w[0],6,$row[0],'LRB',0,'C',$fill);
		$this->Cell($w[1],6,$row[1],'LRB',0,'L',$fill);
		$this->Cell($w[2],6,$row[2],'LRB',0,'R',$fill);
		$this->Cell($w[3],6,$row[3],'LRB',0,'R',$fill);
		$this->Cell($w[3],6,$row[4],'LRB',0,'R',$fill);
		$this->Ln();
		//$this->Cell(array_sum($w),0,'','T'); 
	}

	//Tableau coloré
	function FancyTable($data)
	{
		//Restauration des couleurs et de la police
		$this->SetFillColor(224,235,255);
		$this->SetTextColor(0);
		$this->SetFont('');
		//Données
		$fill=false;
		foreach($data as $row)
		{
			$this->Cell($w[0],6,$row[0],'LR',0,'C',$fill);
			$this->Cell($w[1],6,$row[1],'LR',0,'L',$fill);
			$this->Cell($w[2],6,number_format($row[2],2,',',' ')." ".EURO,'LR',0,'R',$fill);
			$this->Cell($w[3],6,number_format($row[3],2,',',' ')." ".EURO,'LR',0,'R',$fill);
			$this->Ln();
			$fill=!$fill;
		}
		$this->Cell(array_sum($w),0,'','T');
	}
}
?>